name: diabetes_rf_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas==2.0.3
      - numpy==1.24.3
      - scikit-learn==1.3.0
      - mlflow==2.8.1
      - matplotlib==3.7.2
      - seaborn==0.12.2
